language: scala
sudo: false
dist: trusty

# We do not want to start a travis build
# for modifications to any branch.
branches:
    except:
        - develop
    only:
        - master
        - citest

addons:
  apt:
    packages:
    - apt-transport-https
    - wget
    - git
    - openssh-server
    - tree
    - python2.7
    - python-pip
    - maven

before_install:
  - mkdir -p /tmp/ci_tests
  - cd /tmp/ci_tests

install:
  # Clone and make the python and java dxpy version
  - pwd
  - git clone https://github.com/dnanexus/dx-toolkit.git
  - make -C dx-toolkit python java

  # Clone dxWDL into a new directory,
  - pwd
  - git clone https://github.com/dnanexus-rnd/dxWDL.git
  - echo "dxWDL branch = $TRAVIS_BRANCH"
  - cd dxWDL && git checkout $TRAVIS_BRANCH && cd ..
  - ls -R dxWDL
  - mkdir -p dxWDL/lib
  - cp dx-toolkit/lib/java/dnanexus-api-0.1.0-SNAPSHOT-jar-with-dependencies.jar dxWDL/lib/

before_script:
  - cd /tmp/ci_tests

script:
  - pwd
  - source dx-toolkit/environment
  - dx login --token ${DX_AUTH_TOKEN} --noprojects
  - java -version
  - cd dxWDL && sbt version && ./build_jar.py --multi-region
  - pwd

  # Test on the various regions. Don't wait for execution to complete, it
  # takes too long, and travis times out.
  #
  # Test on US-east
  - dx select dxWDL_playground
  - java -jar dxWDL-*.jar compile test/trivial.wdl --destination /travis_ci --force
  - dx run /travis_ci/trivial -y

  # Test on Sydney region
  - dx select dxWDL_Sydney
  - java -jar dxWDL-*.jar compile test/trivial.wdl --destination '/Swiss Cheese/' --force
  - dx run /Swiss\ Cheese/trivial -y

  # Test on Azure region
  - dx select dxWDL_Azure
  - java -jar dxWDL-*.jar compile test/trivial.wdl --force
  - dx run /trivial -y

env:
  global:
    # DX_AUTH_TOKEN (orodeh)
    secure: "rrdCKN1SQv+XJkpkh6jqtkNdX/pCsYj0x627nrrvUIdzkqanda2ETlFOVpsYROcCjqdpxtHE4zhKtg0PH5t/LTyG+TvRh9F0sK44bQnSxL6h+tfXeenunIu6zlqH629GiiR4Jmqn9gq8NncOSXF8D970Yb7XwKQG7HHfKvqsUbLNfSJXHPUMILGkatNsd+wlDLDHbX2N8A53cgG7LDph4asqf/QkUfE9659zUEpA0OLpXrIQAt054OTApgSlTMGciCvDUQfJ1/+B1iW/pTsT3ZCLwEHqCLS0af6zM+UngrEx4lkxj7O8yi063Mwt1UdyEN4clpB5OHgFCJugUIJbuE4QxwjzcwFZyJJfxdljJMUTVzuDnfBlFHenO5dN+uqTBbE1hvpM4nS/GxnPTeNbTOJQKmdlYmo6gc/d5rjGn+V4evW5nSoG2QOq3eoE7ljBqb+0MLnDLEVI7uLvP8wKyuM5Iay97u/nSiK+g8RvSGtZGijDM0HUV1jKYOFnggqghZQwXpKsEcV6ZKOKDrU81shdv0GklmzuZriarUqc+64hO1HE9TRoPgvvEMjsaOXOZWAqJe0tuyf0SyueWHLNjONGeQ1i87TXS5qeGKWlPtRArAqVa5RNey3sKCoEiSkGjksymi5dcFDZockE7saaTydZoVGELAyo1hryxcnY8Ko="